#loginPageUrl=https://webapps.tekstac.com/SeleniumApp1/TrainReservation/login.html
#trainBookingPageUrl = https://webapps.tekstac.com/SeleniumApp1/TrainReservation/index.html
#searchPageUrl = https://webapps.tekstac.com/SeleniumApp1/TrainReservation/search.html
#EnquiryPageUrl = https://webapps.tekstac.com/SeleniumApp1/TrainReservation/contactus.html
#
#
driverPath = src/test/drivers/chromedriver.exe
#browserName=chrome

# Browser Configuration
browserName=chrome

# Application URLs
loginPageUrl=https://webapps.tekstac.com/SeleniumApp1/TrainReservation/login.html
trainBookingPageUrl=https://webapps.tekstac.com/SeleniumApp1/TrainReservation/index.html
searchPageUrl=https://webapps.tekstac.com/SeleniumApp1/TrainReservation/search.html
enquiryPageUrl=https://webapps.tekstac.com/SeleniumApp1/TrainReservation/contactus.html